services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: enterprise-ai
    env_file:
      - .env
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name:
     enterprise-frontend
    
    environment:
      - API_URL=http://backend:8000/ask
      
    ports:
      - "8501:8501"
    depends_on:
      - backend




  